[tool.poetry]
name = "leoss"
version = "0.1.11"
description = "Low Earth Orbit Spacecraft Simulator"
authors = ["space-hiro <144877753+space-hiro@users.noreply.github.com>"]
readme = "README.md"
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
pytest = "^3.10"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
